routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/','App\Http\Controllers\LoginController@index');
Route::post('authenticate','App\Http\Controllers\LoginController@authenticate');
Route::get('/logout','App\Http\Controllers\LoginController@logout');

Route::get('dashboard', function () {
    return view('dashboard');
});


// Route::get('qualification','App\Http\Controllers\QualificationController');
// Route::get('qualification_create','App\Http\Controllers\QualificationController@create');
// Route::post('qualification_submit','App\Http\Controllers\QualificationController@store');
// Route::get('qualification_edit/{id}','App\Http\Controllers\QualificationController@edit');
// Route::post('qualification_update/{id}','App\Http\Controllers\QualificationController@update');
// Route::get('qualification_delete/{id}','App\Http\Controllers\QualificationController@destroy');
// Route::prefix('admin')->middleware('admin')->group(function () {
    // Route::get('qualification', 'App\Http\Controllers\QualificationController@index');
    // Route::get('qualification_create','App\Http\Controllers\QualificationController@create');
    // Route::post('qualification_submit','App\Http\Controllers\QualificationController@store');
    // Route::get('qualification_edit/{id}','App\Http\Controllers\QualificationController@edit');
    // Route::post('qualification_update/{id}','App\Http\Controllers\QualificationController@update');
    // Route::get('qualification_delete/{id}','App\Http\Controllers\QualificationController@destroy');
    Route::resource('qualification', 'App\Http\Controllers\QualificationController');
// });

Route::get('department','App\Http\Controllers\DepartmentController@index');
Route::get('department/create','App\Http\Controllers\DepartmentController@create');
Route::post('department/submit','App\Http\Controllers\DepartmentController@store');
Route::get('department/edit/{id}','App\Http\Controllers\DepartmentController@edit');
Route::post('department/update/{id}','App\Http\Controllers\DepartmentController@update');
Route::get('department/delete/{id}','App\Http\Controllers\DepartmentController@destroy');

Route::get('specialisation','App\Http\Controllers\SpecialisationController@index');

Route::get('specialisation/create','App\Http\Controllers\SpecialisationController@create');
Route::post('specialisation/submit','App\Http\Controllers\SpecialisationController@store');
Route::get('specialisation/edit/{id}','App\Http\Controllers\SpecialisationController@edit');
Route::post('specialisation/update/{id}','App\Http\Controllers\SpecialisationController@update');
Route::get('specialisation/delete/{id}','App\Http\Controllers\SpecialisationController@destroy');

// Route::resource('facility', 'App\Http\Controllers\FacilityController');

Route::prefix('admin')->middleware('admin')->group(function () {
    Route::resource('facility', 'App\Http\Controllers\FacilityController');
});

app/Models/Facility.php
<?php

namespace App\Models;
use App\Models\Company;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Facility extends Model
{
    use HasFactory,SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/FacilityController.php
<?php

namespace App\Http\Controllers;

use App\Models\Facility;
use App\Models\User;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class FacilityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $facil = Facility::all();
       // dd($facil);
        return view('facility.index',['facilities' => $facil]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $user=User::Find(auth::user());
       // dd($user);


       // return view('facility.create',['users'=>$user]);
       return view('facility.create')->with('company',['users'=>$user]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $res=new Facility();
        $res->name=$request->input('name');
        $res->description=$request->input('description');
        $res->user_id=$request->input('user_id');
        $res->company_id=$request->input('company_id');
        // $res->image=$request->input('img');
        $res->fee=$request->input('fee');
        $res->up_date=$request->input('up_date');

        $files = [];

       // dd($request->hasfile('images'));

        if($request->hasfile('images'))
        {

            foreach($request->file('images') as $file)
            {

                $name = time().rand(1,100).'.'.$file->extension();

                $file->move(public_path('product-images'), $name);

                $files[] = $name;

            }

        }

        foreach($files as $f)
        {

            $res->image = $f;
            //$res->product_id = $lastId;
            $res->save();
        }




       // $res->save();
        // dd($res);
        $request->session()->flash('msg','Data saved successfully');
         return redirect('admin/facility');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function show(Facility $facility)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {

        $request=Facility::Find($id);
        // $edi->name=$request->input('name');
        // $edi->save();

    // dd($id);
       return view('facility.edit')->with('facility',Facility::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Facility $facility)
    {

        $res=Facility::find($facility->id);
        // dd($facility->id);
        $res->name=$request->input('name');
        $res->save();
        $request->session()->flash('msg','Data saved successfully');
         return redirect('admin/facility');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Facility  $facility
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {

        Facility::destroy($id);
         $request->session()->flash('msg','Record deleted successfully');
        return redirect('admin/facility');
    }

}

resources/views/facility/create.blade.php
@extends('layouts.app');
@section('content')
<body>
    <div class="container mt-2">
          <h3>Facilities</h3>

          <ul class="nav nav-tabs">
          <li class="nav-item">  <a class="nav-link" href="#">Facilities </a> </li>
          <li class="nav-item">  <a class="nav-link active" href="create">New Facility</a> </li>
          {{session('msg')}}
          <br/>

          </ul>
          <div class="tab-content">
              <div class="container mt-2">
              <form method="post" action="{{ route('facility.store') }}" enctype="multipart/form-data">
                  @csrf
                      <table>

                          <tr>
                              <td>Facility Name :</td>
                              <td> <input type="text" id="name" name="name"></td>
                          </tr>
                          <tr>
                            <td>Description :</td>
                           <td> <textarea name="description" id="description"></textarea></td>
                          </tr>

                          {{-- <tr>
                            <td>User ID:</td>
                            <td> <input type="number" id="user_id" name="user_id"></td>
                          </tr> --}}

                          <tr>
                            <td>User :</td>
                            <td>

                            <select name="user_id" class="form-control">
                                @foreach ($users as $c)
                                    <option value="{{ $c->id }}">{{ $c->name }}</option>
                                @endforeach

                            </select>
                            </td>
                          </tr>
                          <tr>
                            <td>Company :</td>
                            <td>
                                {{$users->company->name}}
                            {{-- <select name="company_id" class="form-control">
                                @foreach ($companies as $c)
                                    <option value="{{ $c->id }}">{{ $c->name }}</option>
                                @endforeach

                            </select> --}}
                        </td>
                          </tr>


                          {{-- <tr>
                            <td>Company ID:</td>
                            <td> <input type="number" id="company_id" name="company_id"></td>
                          </tr> --}}

                          <tr>
                            <td>Fee:</td>
                            <td> <input type="number" id="fee" name="fee"></td>
                          </tr>

                          <tr>
                            <td>Up Date:</td>
                            <td> <input type="date" id="up_date" name="up_date"></td>
                          </tr>

                          <tr>
                            <td>Image:</td>
                            {{-- <td> <input type="text" id="img" name="img"></td> --}}

                            <td><input type="file" multiple name="images[]" id="title"> </td>

                          </tr>

                          <tr>
                              <td> <input type="submit" id="btnsave" name="btnsave"></td>
                          </tr>
                      </table>
                  </form>
              </div>
      </div>

    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</body>
@endsection

resources/views/facility/edit.blade.php
@extends('layouts.app');
@section('content')
<body>
    <div class="container mt-2">
          <h3>Facilities</h3>

          <ul class="nav nav-tabs">
          <li class="nav-item">  <a class="nav-link" href="#">Edit Facility </a> </li>
          <li class="nav-item">  <a class="nav-link active" href="create">New Facility</a> </li>
          {{session('msg')}}
          <br/>

          </ul>
          <div class="tab-content">
              <div class="container mt-2">
              <form method="POST" action="{{ route('facility.update',$facility->id) }}">
                  @csrf
                  {{ method_field('PUT') }}
                      <table>

                          <tr>
                              <td>Facility Name :</td>
                              <td> <input type="text" id="name" name="name" value="{{$facility->name}}"></td>
                          </tr>
                          <tr>
                              <td> <input type="submit" id="btnupd" name="btnupd" value="Save"></td>
                          </tr>
                      </table>
                  </form>
              </div>
      </div>

    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</body>
@endsection

resources/views/facility/index.blade.php
@extends('layouts.app');
@section('content')

    <div class="container mt-2">
          <h3>Departments</h3>

          <ul class="nav nav-tabs">
          <li class="nav-item">  <a class="nav-link active" href="#">Facilities </a> </li>
          <li class="nav-item">  <a class="nav-link" href="facility/create">New Facility</a> </li>
          {{session('msg')}}
          <br/>

          </ul>
          <div>

            <table class="table">
                <thead class="table-dark">
                    <tr>
                    <th>Id</th>
                    <th>Facility</th>
                    <th colspan="2">
                    Actions
                    </th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($facilities as $d)
                    <tr>
                    <td>{{$d->id}}</td>
                    <td>{{$d->name}}</td>
                    <td colspan="2">
                      <form action="{{ route('facility.destroy',$d->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                   <a href="facility/{{$d->id}}/edit"> <i class="bi bi-pencil-square"></i></a>
                   <a href="facility/delete/{{$d->id}}"> <i class="bi bi-eye-fill"></i></a>
                   <button type="submit" class="btn btn-default" ><i class="bi bi-trash"></i></button>

                    {{-- <a href="{{ route('facility.destroy',$d->id) }}"> <i class="bi bi-trash"></i></a> --}}

                 </form>
                    </td>



                 </tr>
                @endforeach
                </tbody>
              </table>
      </div>

    </div>




@endsection

resources/views/facility/index_old.blade.php
@extends('layouts.app');
@section('content')

    <div class="container mt-2">
          <h3>Departments</h3>

          <ul class="nav nav-tabs">
          <li class="nav-item">  <a class="nav-link active" href="#">Facilities </a> </li>
          <li class="nav-item">  <a class="nav-link" href="facility/create">New Facility</a> </li>
          {{session('msg')}}
          <br/>

          </ul>
          <div>

            <table class="table">
                <thead class="table-dark">
                    <tr>
                    <th>Id</th>
                    <th>Facility</th>
                    <th colspan="2">
                    Actions
                    </th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($facilities as $d)
                    <tr>
                    <td>{{$d->id}}</td>
                    <td>{{$d->name}}</td>
                    <td colspan="2">
                    <a href="facility/{{$d->id}}/edit"> <i class="bi bi-pencil-square"></i></a>
                    <a href="facility/{{$d->id}}"> <i class="bi bi-trash"></i></a>
                   <a href="facility/delete/{{$d->id}}"> <i class="bi bi-eye-fill"></i></a>

                    </td>



                 </tr>
                @endforeach
                </tbody>
              </table>
      </div>

    </div>




@endsection